// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUAUuH_tUeqqqdPmKAPMr4Ay1xKo2DAgA',
    appId: '1:160464258753:web:89332faeec34112a5cb640',
    messagingSenderId: '160464258753',
    projectId: 'apiamalia',
    authDomain: 'apiamalia.firebaseapp.com',
    databaseURL: 'https://apiamalia-default-rtdb.firebaseio.com',
    storageBucket: 'apiamalia.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAn_qcB0fVu0c-Y9mKNZH-2b3wXMuVq03E',
    appId: '1:160464258753:android:18bde3210f8573d35cb640',
    messagingSenderId: '160464258753',
    projectId: 'apiamalia',
    databaseURL: 'https://apiamalia-default-rtdb.firebaseio.com',
    storageBucket: 'apiamalia.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbTBGGPBzOP9uNevNB6dUXkrA_VrSHS98',
    appId: '1:160464258753:ios:b6b20c3eab999a325cb640',
    messagingSenderId: '160464258753',
    projectId: 'apiamalia',
    databaseURL: 'https://apiamalia-default-rtdb.firebaseio.com',
    storageBucket: 'apiamalia.firebasestorage.app',
    iosBundleId: 'com.example.latihanmodul5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbTBGGPBzOP9uNevNB6dUXkrA_VrSHS98',
    appId: '1:160464258753:ios:b6b20c3eab999a325cb640',
    messagingSenderId: '160464258753',
    projectId: 'apiamalia',
    databaseURL: 'https://apiamalia-default-rtdb.firebaseio.com',
    storageBucket: 'apiamalia.firebasestorage.app',
    iosBundleId: 'com.example.latihanmodul5',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUAUuH_tUeqqqdPmKAPMr4Ay1xKo2DAgA',
    appId: '1:160464258753:web:6646de307526979d5cb640',
    messagingSenderId: '160464258753',
    projectId: 'apiamalia',
    authDomain: 'apiamalia.firebaseapp.com',
    databaseURL: 'https://apiamalia-default-rtdb.firebaseio.com',
    storageBucket: 'apiamalia.firebasestorage.app',
  );
}
