name: modul_6
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.7
  permission_handler: ^11.3.0
  geolocator: ^9.0.2
  shared_preferences: ^2.2.2
  path_provider: ^2.1.2
  flutter_local_notifications: ^17.0.0
  connectivity_plus: ^6.0.1
  image_gallery_saver:
    git:
      url: https://github.com/hui-z/image_gallery_saver.git
      ref: master

  # firebase_core: ^2.0.0
  # firebase_storage: ^11.0.0
  # dio: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
