name: pember_modul2
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  image_picker: ^0.7.2+1
  # file_picker:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
  - image/img1.jpg
  - image/img2.png
  - image/arrow.png
  - image/profil.png
  - image/upimg.png
  - image/plusimg.png
  - image/location.png

  
