name: praktikum_flutter_kamera
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5+1
  image_picker: ^0.8.7+5
  permission_handler: ^11.0.1
  geolocator: ^11.0.0
  flutter_local_notifications: ^17.0.0
  connectivity_plus: ^6.0.3
  shared_preferences: ^2.2.2
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
