name: app_firebasecli
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.30.0
  cloud_firestore: ^4.17.5
  cupertino_icons: ^1.0.8
  image_picker: ^1.0.0
  font_awesome_flutter: ^10.5.0
  sqflite: ^2.3.0
  path_provider: ^2.1.2
  path: ^1.8.0
  sqlite_viewer: ^1.0.4
  url_launcher: ^6.2.5
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/logo.jpeg
  - assets/gambar1.jpeg
  - assets/gambar2.jpeg
  - assets/gambar3.jpeg
  - assets/gambar4.jpeg
